name: Validate Commit Messages

on:
  push:
    branches:
      - main
      - '**'

jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate commit messages
        run: |
          for commit in $(git log --oneline --pretty=format:"%h"); do
            message=$(git log -1 --pretty=format:"%s" $commit)
            if [[ ! "$message" =~ ^[0-9]+-.* ]]; then
              echo "Commit $commit does not follow the format '(IssueNumber)-(message)': $message"
              exit 1
            fi
          done
